import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Dimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { colors } from '../theme/colors';

const { width } = Dimensions.get('window');

const ReportDetailsScreen = ({ navigation }) => {
    // Hardcoded data based on the image provided
    const date = "OCT 24, 2023";
    const time = "10:45 AM";
    const riskPercentage = 15;
    const isLowRisk = riskPercentage < 30;

    return (
        <SafeAreaView style={styles.container}>
            {/* Header */}
            <View style={styles.header}>
                <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
                    <Ionicons name="chevron-back" size={28} color="#000" />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>Report Details</Text>
                <View style={{ width: 28 }} />
            </View>

            <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>

                {/* Date Header */}
                <View style={styles.dateContainer}>
                    <Ionicons name="calendar-outline" size={14} color="#666" style={{ marginRight: 6 }} />
                    <Text style={styles.dateText}>{date} • {time}</Text>
                </View>

                {/* Main Risk Card */}
                <View style={styles.riskCard}>
                    <Text style={styles.riskLabel}>RISK LEVEL</Text>
                    <Text style={styles.riskValue}>{riskPercentage}%</Text>

                    <View style={styles.riskBadge}>
                        <View style={styles.riskIconCircle}>
                            <Ionicons name="checkmark" size={10} color="#FFF" />
                        </View>
                        <Text style={styles.riskBadgeText}>Low Risk</Text>
                    </View>
                </View>

                {/* Summary Section */}
                <View style={styles.sectionHeader}>
                    <MaterialCommunityIcons name="text-box-outline" size={20} color={colors.primary} />
                    <Text style={styles.sectionTitle}>Summary</Text>
                </View>

                <View style={styles.summaryCard}>
                    <Text style={styles.summaryText}>
                        The analysis of your acoustic data and symptoms indicates a low probability of active tuberculosis. Your breathing patterns and cough characteristics (if recorded) are within normal baseline ranges for non-TB symptomatic profiles.
                    </Text>
                </View>

                {/* Recommendation Section */}
                <View style={styles.sectionHeader}>
                    <MaterialCommunityIcons name="checkbox-marked-circle-outline" size={20} color={colors.primary} />
                    <Text style={styles.sectionTitle}>Recommendation</Text>
                </View>

                {/* Recommendation Cards */}
                <View style={styles.recommendationList}>
                    {/* Item 1 */}
                    <View style={styles.recommendationItem}>
                        <View style={[styles.recIconBox, { backgroundColor: '#E1F5FE' }]}>
                            <Ionicons name="analytics" size={24} color={colors.primary} />
                        </View>
                        <View style={styles.recContent}>
                            <Text style={styles.recTitle}>Monitor Symptoms</Text>
                            <Text style={styles.recDesc}>
                                Keep track of your health over the next 14 days. Re-screen if symptoms persist.
                            </Text>
                        </View>
                    </View>

                    {/* Item 2 */}
                    <View style={styles.recommendationItem}>
                        <View style={[styles.recIconBox, { backgroundColor: '#E0F2F1' }]}>
                            <MaterialCommunityIcons name="shield-plus" size={24} color="#009688" />
                        </View>
                        <View style={styles.recContent}>
                            <Text style={styles.recTitle}>Preventative Care</Text>
                            <Text style={styles.recDesc}>
                                Maintain good ventilation in living areas and practice regular hand hygiene.
                            </Text>
                        </View>
                    </View>
                </View>

                {/* Disclaimer */}
                <Text style={styles.disclaimerText}>
                    DISCLAIMER: This report is generated by an AI screening tool and is NOT a medical diagnosis. Results should be reviewed by a qualified healthcare professional. Always seek medical advice for any health concerns.
                </Text>

                {/* Action Buttons */}
                <View style={styles.actionButtonsContainer}>
                    <TouchableOpacity style={styles.downloadButton}>
                        <Ionicons name="download-outline" size={20} color="#FFF" style={{ marginRight: 8 }} />
                        <Text style={styles.actionButtonText}>Download PDF</Text>
                    </TouchableOpacity>

                    <TouchableOpacity style={styles.shareButton}>
                        <Ionicons name="share-social-outline" size={20} color="#FFF" style={{ marginRight: 8 }} />
                        <Text style={styles.actionButtonText}>Share Report</Text>
                    </TouchableOpacity>
                </View>

                {/* Back to Home Link */}
                <TouchableOpacity
                    style={styles.homeLink}
                    onPress={() => navigation.navigate('MainTabs')}
                >
                    <Text style={styles.homeLinkText}>Back to Home</Text>
                </TouchableOpacity>

            </ScrollView>
        </SafeAreaView>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5F5F5', // Light grey background for this screen as per partial view, or stick to white. Let's try slightly off-white/grey to make white cards pop.
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 12,
        backgroundColor: '#FFFFFF',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#000',
    },
    backButton: {
        padding: 4,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 40,
        paddingTop: 20,
    },
    dateContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    dateText: {
        fontSize: 12,
        color: '#666',
        fontWeight: '500',
        letterSpacing: 0.5,
    },
    riskCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 30,
        alignItems: 'center',
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    riskLabel: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#999',
        letterSpacing: 1.5,
        marginBottom: 8,
        textTransform: 'uppercase',
    },
    riskValue: {
        fontSize: 56,
        fontWeight: 'bold',
        color: '#000',
        marginBottom: 16,
    },
    riskBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9', // Light green
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
    },
    riskIconCircle: {
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: '#2ECC71', // Green
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    riskBadgeText: {
        color: '#2ECC71',
        fontWeight: 'bold',
        fontSize: 14,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
        marginTop: 4,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#000',
        marginLeft: 8,
    },
    summaryCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#EFEFEF',
    },
    summaryText: {
        fontSize: 14,
        color: '#555',
        lineHeight: 22,
    },
    recommendationList: {
        marginBottom: 24,
    },
    recommendationItem: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#EFEFEF',
    },
    recIconBox: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    recContent: {
        flex: 1,
    },
    recTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#000',
        marginBottom: 4,
    },
    recDesc: {
        fontSize: 12,
        color: '#666',
        lineHeight: 18,
    },
    disclaimerText: {
        fontSize: 10,
        color: '#AAA',
        fontStyle: 'italic',
        textAlign: 'center',
        lineHeight: 16,
        marginBottom: 24,
        paddingHorizontal: 10,
    },
    actionButtonsContainer: {
        gap: 12,
        marginBottom: 20,
    },
    downloadButton: {
        backgroundColor: colors.primary, // Blue
        borderRadius: 30,
        paddingVertical: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        elevation: 4,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    shareButton: {
        backgroundColor: '#26A69A', // Teal-ish green
        borderRadius: 30,
        paddingVertical: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 4,
        shadowColor: '#26A69A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    actionButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    homeLink: {
        padding: 12,
        alignItems: 'center',
    },
    homeLinkText: {
        color: '#666',
        fontSize: 14,
        fontWeight: '600',
    },
});

export default ReportDetailsScreen;
