import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Dimensions, Share, Alert, Platform } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { colors } from '../theme/colors';
import { useTranslation } from 'react-i18next';

const { width } = Dimensions.get('window');

const ReportDetailsScreen = ({ navigation }) => {
    const { t } = useTranslation();
    // Hardcoded data based on the image provided
    const date = "OCT 24, 2023";
    const time = "10:45 AM";
    const riskPercentage = 15;
    const isLowRisk = riskPercentage < 30;

    const handleDownloadPDF = async () => {
        try {
            const html = `
                <html>
                  <head>
                    <style>
                      body { font-family: sans-serif; padding: 20px; }
                      h1 { color: #333; }
                      .risk-card { padding: 20px; background-color: #f0f0f0; border-radius: 10px; margin-bottom: 20px; }
                      .risk-value { font-size: 40px; font-weight: bold; color: #000; }
                      .section { margin-bottom: 20px; }
                      .disclaimer { font-size: 10px; color: #888; font-style: italic; margin-top: 40px; }
                    </style>
                  </head>
                  <body>
                    <h1>${t('report_title')}</h1>
                    <p>Date: ${date} • Time: ${time}</p>
                    
                    <div class="risk-card">
                        <p>${t('report_risk_level')}</p>
                        <div class="risk-value">${riskPercentage}%</div>
                        <p>${t('report_low_risk')}</p>
                    </div>

                    <div class="section">
                        <h3>${t('report_summary_title')}</h3>
                        <p>${t('report_summary_text')}</p>
                    </div>

                    <div class="section">
                        <h3>${t('report_recommendation_title')}</h3>
                        <ul>
                            <li><strong>${t('report_rec_1_title')}</strong>: ${t('report_rec_1_desc')}</li>
                            <li><strong>${t('report_rec_2_title')}</strong>: ${t('report_rec_2_desc')}</li>
                        </ul>
                    </div>

                    <div class="disclaimer">
                        ${t('report_disclaimer')}
                    </div>
                    <p><small>Generated by SwaaS</small></p>
                  </body>
                </html>
            `;

            const { uri } = await Print.printToFileAsync({ html });

            if (Platform.OS === 'android') {
                const permissions = await FileSystem.StorageAccessFramework.requestDirectoryPermissionsAsync();
                if (permissions.granted) {
                    const base64 = await FileSystem.readAsStringAsync(uri, { encoding: FileSystem.EncodingType.Base64 });
                    await FileSystem.StorageAccessFramework.createFileAsync(permissions.directoryUri, 'SwaaS_Report.pdf', 'application/pdf')
                        .then(async (createdUri) => {
                            await FileSystem.writeAsStringAsync(createdUri, base64, { encoding: FileSystem.EncodingType.Base64 });
                            Alert.alert(t('alert_success'), "Report saved successfully!");
                        })
                        .catch(e => {
                            console.log(e);
                            Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
                        });
                } else {
                    Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
                }
            } else {
                await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
            }
        } catch (error) {
            Alert.alert(t('alert_error'), "Failed to generate PDF");
        }
    };

    const handleShareReport = async () => {
        try {
            const message = `${t('report_title')}\n` +
                `${t('report_risk_level')}: ${riskPercentage}% (${t('report_low_risk')})\n\n` +
                `${t('report_summary_title')}: ${t('report_summary_text')}\n\n` +
                `SwaaS`;

            await Share.share({
                message,
            });
        } catch (error) {
            Alert.alert(t('alert_error'), "Failed to share report");
        }
    };

    return (
        <SafeAreaView style={styles.container}>
            {/* Header */}
            <View style={styles.header}>
                <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
                    <Ionicons name="chevron-back" size={28} color="#000" />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>{t('report_title')}</Text>
                <View style={{ width: 28 }} />
            </View>

            <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>

                {/* Date Header */}
                <View style={styles.dateContainer}>
                    <Ionicons name="calendar-outline" size={14} color="#666" style={{ marginRight: 6 }} />
                    <Text style={styles.dateText}>{date} • {time}</Text>
                </View>

                {/* Main Risk Card */}
                <View style={styles.riskCard}>
                    <Text style={styles.riskLabel}>{t('report_risk_level')}</Text>
                    <Text style={styles.riskValue}>{riskPercentage}%</Text>

                    <View style={styles.riskBadge}>
                        <View style={styles.riskIconCircle}>
                            <Ionicons name="checkmark" size={10} color="#FFF" />
                        </View>
                        <Text style={styles.riskBadgeText}>{t('report_low_risk')}</Text>
                    </View>
                </View>

                {/* Summary Section */}
                <View style={styles.sectionHeader}>
                    <MaterialCommunityIcons name="text-box-outline" size={20} color={colors.primary} />
                    <Text style={styles.sectionTitle}>{t('report_summary_title')}</Text>
                </View>

                <View style={styles.summaryCard}>
                    <Text style={styles.summaryText}>
                        {t('report_summary_text')}
                    </Text>
                </View>

                {/* Recommendation Section */}
                <View style={styles.sectionHeader}>
                    <MaterialCommunityIcons name="checkbox-marked-circle-outline" size={20} color={colors.primary} />
                    <Text style={styles.sectionTitle}>{t('report_recommendation_title')}</Text>
                </View>

                {/* Recommendation Cards */}
                <View style={styles.recommendationList}>
                    {/* Item 1 */}
                    <View style={styles.recommendationItem}>
                        <View style={[styles.recIconBox, { backgroundColor: '#E1F5FE' }]}>
                            <Ionicons name="analytics" size={24} color={colors.primary} />
                        </View>
                        <View style={styles.recContent}>
                            <Text style={styles.recTitle}>{t('report_rec_1_title')}</Text>
                            <Text style={styles.recDesc}>
                                {t('report_rec_1_desc')}
                            </Text>
                        </View>
                    </View>

                    {/* Item 2 */}
                    <View style={styles.recommendationItem}>
                        <View style={[styles.recIconBox, { backgroundColor: '#E0F2F1' }]}>
                            <MaterialCommunityIcons name="shield-plus" size={24} color="#009688" />
                        </View>
                        <View style={styles.recContent}>
                            <Text style={styles.recTitle}>{t('report_rec_2_title')}</Text>
                            <Text style={styles.recDesc}>
                                {t('report_rec_2_desc')}
                            </Text>
                        </View>
                    </View>
                </View>

                {/* Disclaimer */}
                <Text style={styles.disclaimerText}>
                    {t('report_disclaimer')}
                </Text>

                {/* Action Buttons */}
                <View style={styles.actionButtonsContainer}>
                    <TouchableOpacity style={styles.downloadButton} onPress={handleDownloadPDF}>
                        <Ionicons name="download-outline" size={20} color="#FFF" style={{ marginRight: 8 }} />
                        <Text style={styles.actionButtonText}>{t('report_download')}</Text>
                    </TouchableOpacity>

                    <TouchableOpacity style={styles.shareButton} onPress={handleShareReport}>
                        <Ionicons name="share-social-outline" size={20} color="#FFF" style={{ marginRight: 8 }} />
                        <Text style={styles.actionButtonText}>{t('report_share')}</Text>
                    </TouchableOpacity>
                </View>

                {/* Back to Home Link */}
                <TouchableOpacity
                    style={styles.homeLink}
                    onPress={() => navigation.navigate('MainTabs')}
                >
                    <Text style={styles.homeLinkText}>{t('report_back_home')}</Text>
                </TouchableOpacity>

            </ScrollView>
        </SafeAreaView>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5F5F5', // Light grey background for this screen as per partial view, or stick to white. Let's try slightly off-white/grey to make white cards pop.
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 12,
        backgroundColor: '#FFFFFF',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#000',
    },
    backButton: {
        padding: 4,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 40,
        paddingTop: 20,
    },
    dateContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    dateText: {
        fontSize: 12,
        color: '#666',
        fontWeight: '500',
        letterSpacing: 0.5,
    },
    riskCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 30,
        alignItems: 'center',
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    riskLabel: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#999',
        letterSpacing: 1.5,
        marginBottom: 8,
        textTransform: 'uppercase',
    },
    riskValue: {
        fontSize: 56,
        fontWeight: 'bold',
        color: '#000',
        marginBottom: 16,
    },
    riskBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9', // Light green
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
    },
    riskIconCircle: {
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: '#2ECC71', // Green
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    riskBadgeText: {
        color: '#2ECC71',
        fontWeight: 'bold',
        fontSize: 14,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
        marginTop: 4,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#000',
        marginLeft: 8,
    },
    summaryCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#EFEFEF',
    },
    summaryText: {
        fontSize: 14,
        color: '#555',
        lineHeight: 22,
    },
    recommendationList: {
        marginBottom: 24,
    },
    recommendationItem: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#EFEFEF',
    },
    recIconBox: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    recContent: {
        flex: 1,
    },
    recTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#000',
        marginBottom: 4,
    },
    recDesc: {
        fontSize: 12,
        color: '#666',
        lineHeight: 18,
    },
    disclaimerText: {
        fontSize: 10,
        color: '#AAA',
        fontStyle: 'italic',
        textAlign: 'center',
        lineHeight: 16,
        marginBottom: 24,
        paddingHorizontal: 10,
    },
    actionButtonsContainer: {
        gap: 12,
        marginBottom: 20,
    },
    downloadButton: {
        backgroundColor: colors.primary, // Blue
        borderRadius: 30,
        paddingVertical: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        elevation: 4,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    shareButton: {
        backgroundColor: '#26A69A', // Teal-ish green
        borderRadius: 30,
        paddingVertical: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 4,
        shadowColor: '#26A69A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    actionButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    homeLink: {
        padding: 12,
        alignItems: 'center',
    },
    homeLinkText: {
        color: '#666',
        fontSize: 14,
        fontWeight: '600',
    },
});

export default ReportDetailsScreen;
